
# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: git config --global user.email $GIT_COMMITTER_EMAIL
  - init: npm install --global @bazel/bazelisk
